name: Build System Image (beta-dev_nv)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Prepare build environment
        env:
          storageBoxLink: ${{ secrets.STORAGE_BOX_LINK }}
          storageBoxPassword: ${{ secrets.STORAGE_BOX_PASSWORD }}
        run: |
          pacman-key --init
          pacman --noconfirm -Syu btrfs-progs archiso git reflector sshfs
          git clone https://github.com/holoiso-staging/buildroot buildroot
          git clone https://github.com/holoiso-staging/postcopy -b dev_nv buildroot/postcopy_beta-dev_nv
          mkdir /mnt/build
          echo "$storageBoxPassword" | sshfs -o password_stdin -oStrictHostKeyChecking=no "$storageBoxLink":/ /mnt/build
      - name: Build image 
        run: |
          mkdir -p $(pwd)/workdir /mnt/build/holoiso-images
          bash buildroot/build.sh --flavor beta-dev_nv --deployment_rel beta-dev_nv --snapshot_ver "${GITHUB_REF_NAME}" --workdir $(pwd)/workdir --output-dir /mnt/build/holoiso-images --add-release
