name: playground
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10
        
      - name: Prepare build environment
        run: |
          df -h
          
