name: playground
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Prepare build environment
        run: |
          df -h
          ls -ltha /usr/bin
          pacman -Q
          
